{% set version = "0.2.3" %}

package:
  name: wcwidth
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wcwidth/wcwidth-{{ version }}.tar.gz
  sha256: edbc2b718b4db6cdf393eefe3a420183947d6aa312505ce6754516f458ff8830

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - wcwidth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jquast/wcwidth
  license: MIT
  license_file: LICENSE
  summary: Measures number of Terminal column cells of wide-character codes.

extra:
  recipe-maintainers:
    - ocefpaf
