travis:
  secure:
    BINSTAR_TOKEN: DNjZofQq7qpDbWtJwuthFNuKxuPpjYvKL8rNkzcPOCaGyWyaQk154fn5TmILtDWgeNlAJdRJxtIfPJg5ohi2oGTglUy/VLXcsUloB0tZYkMr8U7k/DaNcQgBup0uHDokoGKWRj3p6b4XIaBpMff3sqJ/Mocoad0oxjX7JkmJbZMKofIdGFZxToMFKg5hppqrr0ZK4XzlXPGrI50Nmo29HPlYJxLflTjykKEEBNfxX3TI1oh5i4Dyr/t9vlGMUZ3TwEr3XFpg3s/OCaKi744JFpxs4LjjV27+VAVLEtKqwTV9kUAO3iBz3GzmhVgP1Y8lrIpXtfpArri0wHD/hpTcYVAl4ma+oWUC35DAUEoa2xYRUWRNQPaxT3+FjD8CU/a9eHLVhNCJVHLSAj+u1TrbVH+Q9Jo+eVnHwxE3AmSgEw30J8WDK07ec9UwkXjx/0rCWByWlxywy92F0+n6GAARay0Msk/5wzP5lm7F9mqUteObijr5Sk5IekDffQZ/Thy5OI4VWQ0vFWAU0iiSyVHJvCMMXB9XJhBCkzMb3Or9/nsKcfbgX27PWf29ZXSCDEor50VVMJDXjLRCSK+1Uy7OcBMaDjjFUXW4pRMhnURnu9kQpD2OhpbTAuSbf8W58dedcS5ChbccTryM+JrakXIgCbv8+JCoB3XqEjMuZfupx1g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
